CBT/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView, TemplateView
urlpatterns = patterns('myproject.CBT.views',
    
    url(r'^home/$', 'chroose'),
    url(r'^set_user/subject/$', 'assignment'),
    url(r'^schedulling/active/$', 'cbtstat'),

    ###****questions************
    url(r'^enter/question/$', 'qstn'),
    url(r'^enter/image/(\d+)/$', 'cbtimage'),
    url(r'^enter/ajaxclass/$', 'ajaxclass'),
    url(r'^getcbtsubject/$', 'getcbtsubject'),
    url(r'^enter/question/getqstn/$', 'getcbtqst'),
    
    url(r'^enter/question/ajax/$', 'editcbtqst'),

    url(r'^enter/question/majax/$', 'editcbtpix'),

##*******options *******************
    url(r'^enter/options/getopt/$', 'getcbtopt'),
    url(r'^options/$', 'options'),
    url(r'^options/options/(\d+)/$', 'myoptions'),
    url(r'^options/options/image/(\d+)/$', 'myoptionsimage'),
    url(r'^options/enteropt/$', 'optajax'),
    url(r'^options/choose/$', 'chooseopt'),
    url(r'^options/texts/(\d+)/$', 'textts'),
    url(r'^input_text/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/$', 'save_text'),
    url(r'^options/images/(\d+)/$', 'images'),
    url(r'^input_images/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/$', 'save_images'),


#***--------------theory------------------
    url(r'^enter/theory/$', 'theory'),

    ##****** student's view**************
    url(r'^cbt/exam/$', 'exxxam'),
    url(r'^take_test/start/$', 'pupilcbt'),
    url(r'^take_test/next/$', 'next'),
    url(r'^take_test/clear/$', 'clear'),
    url(r'^take_test/previous/$', 'beefore'),
    url(r'^take_test/skip/$', 'skip'),

    ##*******edit *******************
    url(r'^enter/options/edit/$', 'editquestion'),
    url(r'^edit/$', 'editq'),
  
    url(r'^edit/editentry/$', 'doentry'),


    url(r'^edit/editqst/$', 'editqst'),
    url(r'^change/question/(\d+)/$', 'changeqst'),


    url(r'^edit/edita/$', 'editoptiona'),
    url(r'^change/optiona/(\d+)/$', 'optiona'),

    url(r'^edit/editb/$', 'editoptionb'),
    url(r'^change/optionb/(\d+)/$', 'optionb'),

    url(r'^edit/editc/$', 'editoptionc'),
    url(r'^change/optionc/(\d+)/$', 'optionc'),

    url(r'^edit/editd/$', 'editoptiond'),
    url(r'^change/optiond/(\d+)/$', 'optiond'),

    url(r'^edit/imageqst/$', 'sdfgsf'),


    url(r'^question/imageedit/(\d+)/$', 'chngqstimage'),

#**********##mark guides*********************
    url(r'^mark_guides/$', 'markguide'),

    url(r'^markguide/getmg/$', 'guides'),    

    url(r'^assessment/set/$', 'setass'),  

    #***************schedulling####
    url(r'^assess/getassess/$', 'getassessment'),
    url(r'^getsubject/$', 'getcbtsub'),
    url(r'^getscheduledsubject/$', 'getscheduledsubject'), 
    url(r'^getcbtklass/$', 'getcbtklass'), 


###***User***********
url(r'^finduser/$', 'autocomplete'), 
    )

assessment/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('myproject.assessment.views',
    # Examples:
    url(r'^enterca/$', 'enterca'),#Continueous Assessment for Secondary School
    url(r'^ca_comments/$','commentca'),
    url(r'^getclass/$', 'getclass'),
    url(r'^stucacom/$','stucom'),
    url(r'^student/my_subjects/$','mysubjects'),
    url(r'^student/my_subject_page/$','mysubjectpage'),
    url(r'^student/my_results/$','my_results'),
    url(r'^student/my_results_page/$','my_results_page'),
    url(r'^student/myassess/$', 'myassess'),
    url(r'^sn/class_notes/$', 'stunotes'),
    url(r'^sn/pq/$', 'pq'),
    url(r'^student/mybills/$', 'mybills'),
    # url(r'^lib/choose/$', 'options'),
    url(r'^student/printmybills/$', 'printmybill'),
    url(r'^student/mystudykit/$', 'mystudykit'),
    url(r'^student/mycomm/$', 'mycomm'),
    url(r'^student/ca_student/$', 'castudent'),
    url(r'^wel/$', 'wel'),
    url(r'^pupil/scripts/$', 'my_scripts'),

 

    url(r'^class_list/$', 'classlist'),
    url(r'^half_term/$', 'halfterm'),

    url(r'^getmycourse/$', 'hgkvkuu'),
    url(r'^stucourseform/$', 'stucourseform'),               

    url(r'^getarm/$', 'getarm'),
    url(r'^getarmgrp/$', 'getarmgroup'),
    url(r'^getterm/$', 'getterm'),
    url(r'^getsubject/$', 'getsubject'),
    url(r'^getstusubject/$', 'getstusubject'),
    url(r'^getsubjectless/$', 'getsubjectlesson'),
    url(r'^getstudent/$', 'getstudent'),
    url(r'^getassign/$', 'getassign'),
    url(r'^editca/(\d+)/$', 'editca'),
    
    url(r'^editcas/(\d+)/$', 'editcas'),  #End term magana***************

    url(r'^editcas2/(\d+)/$', 'editcas2'),   #mid term magana***************
   
    url(r'^teacherrport/$', 'teacher_report'),
    url(r'^editcap/(\d+)/$', 'editcapry'),
    url(r'^getsubjectscore/$', 'getsubjectscore'),
    url(r'^getsubjectscore1/$', 'getsubjectscore1'),
    url(r'^getsubjectscore2/$', 'getsubjectscore2'),
    url(r'^getsubjectscorep/$', 'getsubjectscorep'),
    url(r'^getclassaff/$', 'getclassaff'),
    url(r'^getarmaff/$', 'getarmaff'),    
    url(r'^affective/$', 'affectivedomain'),
    url(r'^courseform/(\d+)/$', 'studentcourseform'),
    url(r'^getstudentaff/$', 'getstudentaff'),
    url(r'^classlist/$', 'getstudentlist'),
    url(r'^getcomment/$', 'getcomment'),
    url(r'^comment/$', 'getcomm'),
    url(r'^getmycomment/$', 'comment'),
    url(r'^getstucomment/$', 'getcomment'),
    url(r'^getstucommentca/$', 'getcommentca'),
    url(r'^getaffective/$', 'getaffective'),
    url(r'^getpsyco/$', 'getpsyco'),
    url(r'^getsubgroup/$', 'changesubgrp'),
    url(r'^editgrp/(\d+)/$', 'editsubgrp'),


    url(r'^editcomment/(\d+)/$', 'editcomment'),
    url(r'^editcommentca1/(\d+)/$','editcommentca1'),
    url(r'^editcommentca2/(\d+)/$','editcommentca2'),
    url(r'^editpsyco/(\d+)/$', 'editpsyco'),
    url(r'^editaffective/(\d+)/$', 'editaffective'),
    url(r'^addsubject/$', 'addsubject'),
    url(r'^getstudentsubject/$', 'getstudentsubject'),
    url(r'^getsubject4student/$', 'getsubject4student'),
    url(r'^getmoresubject/$', 'getmoresubject'),
    url(r'^getmorestudentsubject/$', 'getmorestudentsubject'),
    url(r'^addmoresubject/$', 'addmoresubject'),
    url(r'^deletemoresubject/$', 'deletemoresubject'),
    url(r'^confirmdeletemoresubject/(\d+)/$', 'confirmdeletemoresubject'),
    url(r'^principalcomment/$', 'principalcomment'),
    url(r'^getstudentprinicipalcomment/$', 'getstudentprincipalcomment'),
    url(r'^getprinicipalcomment/$', 'getprincipalcomment'),
    url(r'^editcommentprin/(\d+)/$', 'editcommentprin'),
    url(r'^getstudentacademic/$', 'getstudentacademic'),
    url(r'^entercapry/$', 'addsubject4pry'),#Continueous Assessment for Primary School
    url(r'^primary_assessment/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/$', 'primary_url'),#primary school redirecting
    
    # url(r'^secondary_assessment/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/$', 'secondary_url'),#secondary school redirecting

    url(r'^secondary_assessment/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/$', 'secondary_url'),#secondary school redirecting

    url(r'^secondary_print_assessment/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/(\w+)/$', 'secondary_teacher_report'),#secondary school redirecting

    url(r'^secondary_cf/(\w+)/(\w+)/(\w+)/$', 'secondary_cf'),# cf redirecting for secondary

    url(r'^getsubject4studentpry/$', 'getsubject4studentpry'),
    url(r'^getclassaffpry/$', 'getclassaffpry'),
    url(r'^reportsheet/$', 'reportsheet'),
    url(r'^reportopt/$', 'reportopt'),
    url(r'^indreport/$', 'indreport'),
    url(r'^mid-term-report/$', 'reportsheetmidterm'),
    url(r'^broadsheet/$', 'broadsheet'),
    url(r'^mid-term-broadsheet/$', 'mid_term_broadsheet'),
    url(r'^access-denied/$', 'unautho'),

)

urls.py
from django.conf.urls.defaults import *
from myproject.signals import *
from django.conf import settings
# from myproject.geo.views import *
from myproject.sysadmin.views import *
from myproject.setup.views import *
from myproject.utilities.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', index),
    url(r'^login/$', index),
    url(r'^header/$', header),
    url(r'^welcome/$', welcomecode),
    url(r'^online/$', online_result),
    url(r'^subject_report/$', subject_report),
    url(r'^student_search/$', search_student),
    url(r'^logout/$', logoutuser),
    url(r'^unauthorised/$', unatho),
    url(r'^uploadlga/$',uploadlocal ),
    url(r'^uploadsubgroup/$',uploadaccsubgrp),
    url(r'^uploadacc/$',uploadacc),
    url(r'^home_dashboard/$',dashboard),
    url(r'^uploadtransaction/$',uploadtransaction),
    url(r'^pass_change/$', change_password),
    url(r'^getchangepassword/$', getchangepassword),
    url(r'^uploadstudent/$',uploadstudent),
    url(r'^uploadbill/$',uploadbill),#to upload bill setup
    url(r'^uploadbillname/$',uploadbillname),#to upload bill name
    url(r'^uploadadditionalbill/$',uploadadditionalbill),#to upload  additional bills
    url(r'^uploadpostedbill/$',uploadpostedbill),#to upload posted bill

    url(r'^changepassword/$', changepassword),
    url(r'^setup/', include('myproject.setup.urls')),
        url(r'^geo/', include('myproject.geo.urls')),
    url(r'^student/', include('myproject.student.urls')),
    url(r'^bill/', include('myproject.bill.urls')),
    url(r'^cbt/', include('myproject.CBT.urls')),
    url(r'^sysadmin/', include('myproject.sysadmin.urls')),
    url(r'^controllers/', include('myproject.sysadmin.urls')),
    url(r'^assessment/', include('myproject.assessment.urls')),

    url(r'^lesson/', include('myproject.lesson.urls')),
    
    url(r'^assignment/', include('myproject.assignment.urls')),
   # url(r'^transport/', include('myproject.transport.urls')),
    url(r'^utils/', include('myproject.utilities.urls')),

    # url(r'^__debug__/', include(debug_toolbar.urls)),

    
    # Uncomment the admin/doc line below to enable admin documentation:
   # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),

    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

CBT/models.py
from django.db import models


from student.models import Student





state = terms_list = (('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'))

# Create your models here.


class tblquestion(models.Model):
    exam_type = models.CharField('Exam Type', max_length=375)
    subject = models.CharField('Subject', max_length=75)
    session = models.CharField('Session', max_length=75, null=True, blank=True)
    klass = models.CharField('Class', max_length=20)
    term = models.CharField('Term',max_length=10)
    topic = models.CharField('Topic',max_length=1000, null=False,blank=True)
    instruction_from = models.CharField('From', max_length=975)
    instruction_to = models.CharField('From', max_length=975)
    qstn = models.CharField('Question', max_length=975)
    image = models.ImageField('Image', upload_to='questions', null=True,blank=True,default='studentpix/user.png')
    section = models.CharField('Section', max_length=20,default=0)


    def __unicode__(self):
        return '%s %s %s'%(self.exam_type,self.subject,self.qstn)



class tblcbtexams(models.Model):
    exam_type = models.CharField('Exam Type', max_length=375)
    status = models.CharField('Status', max_length=75, null=False, blank=False)
    # term = models.CharField('Term',max_length=10)


    def __unicode__(self):
        return '%s %s'%(self.exam_type,self.status)
        #ession,self.term)



class tbloptions(models.Model):
    qstn = models.ForeignKey(tblquestion, related_name='Options')
    a = models.CharField('Option A', max_length=7500)
    b = models.CharField('Option B', max_length=7500)
    c = models.CharField('Option C', max_length=7500)
    d = models.CharField('Option D', max_length=7500)
    e = models.CharField('Option E', max_length=7500)


    def __unicode__(self):
        return u'%s %s %s %s'%(self.a,self.b,self.c,self.d)    
  


class tbloptioni(models.Model):
    qstn = models.ForeignKey(tblquestion, related_name='Optioni')
    a = models.ImageField('Image', upload_to='questions',default='questions/user.png')
    b = models.ImageField('Image', upload_to='questions', default='questions/user.png')
    c = models.ImageField('Image', upload_to='questions', default='questions/user.png')
    d = models.ImageField('Image', upload_to='questions',default='questions/user.png')
    e = models.ImageField('Image', upload_to='questions',default='questions/user.png')


    def __unicode__(self):
        return u'%s %s %s %s'%(self.a,self.b,self.c,self.d)



class tblans(models.Model):
    qstn = models.ForeignKey(tblquestion, related_name='Transaction')
    ans = models.CharField('Answer', max_length=75)
    option = models.CharField('Option', max_length=7500,default=0)

    def __unicode__(self):
        return u' a : %s, b:  %s ' % (self.ans, self.option)


class tbltheory(models.Model):
	exam_type = models.CharField('Exam Type', max_length=375)
	subject = models.CharField('Subject', max_length=75)
	session = models.CharField('Session', max_length=75, null=True, blank=True)
	klass = models.CharField('Class', max_length=20)
	term = models.CharField('Term',max_length=10)
	topic = models.CharField('Topic',max_length=375,null=True,blank=True)
	instruction_to = models.CharField('From', max_length=975)
	instruction_from = models.CharField('From', max_length=975)
	image = models.ImageField('Image', upload_to='questions', null=True,blank=True,default='questions/user.png')


	def __unicode__(self):
		return u' exam_type : %s ,subject : %s , term : %s , to  : %s' % (self.exam_type,self.subject,self.term,self.instruction_from)


class tblcbtuser(models.Model):
    session = models.CharField('Session', max_length=75, null=True, blank=True)
    klass = models.CharField('Class', max_length=20)
    subject = models.CharField('Subject',max_length=10)
    user = models.CharField('User',max_length=375,null=True,blank=True)


    def __unicode__(self):
    	return u' exam : %s ,subject : %s , term : %s , d  : %s' % (self.exam_type,self.subject,self.c,self.term)



class tblcbtsubject(models.Model):
    duration = models.CharField('Duration', max_length=375)
    subject = models.CharField('Subject', max_length=75)
    session = models.CharField('Session', max_length=75, null=True, blank=True)
    klass = models.CharField('Class', max_length=20)
    term = models.CharField('Term',max_length=10)
    exam_type = models.CharField('Exam_type', max_length=75)
    status = models.CharField('Status',null=True,blank=True,max_length=60,default='INACTIVE')



    def __unicode__(self):

    	return u'%s-%s' % (self.subject,self.term)


class cbttrans(models.Model):
    session = models.CharField('Session', max_length=375)
    exam_type = models.CharField('Exam_type', max_length=75)
    student = models.ForeignKey(Student, max_length=75, null=True, blank=True)
    subject = models.CharField('Subject', max_length=20)
    term = models.CharField('Term',max_length=10)
    question = models.ForeignKey(tblquestion,null=False,blank=False,choices=state,default='INACTIVE')
    stu_ans = models.CharField('Answer',max_length=10)
    score = models.IntegerField('Score', default=0)
    qstcode = models.CharField('Question ID',default=0,max_length=10)
    status = models.CharField('Status',default=0,max_length=10)
    no = models.CharField('Count',default=0,max_length=10)
    mark = models.ImageField('Mark', upload_to='studentpix', null=False,blank=False,default='studentpix/user.png')

    def __unicode__(self):
        return u'%s-%s-%s' %(self.exam_type,self.subject,self.score)



class scheduled(models.Model):
    session = models.CharField('Session', max_length=375)
    assessment = models.CharField('Exam_type', max_length=75)
    student = models.ForeignKey(Student, max_length=75, null=True, blank=True)
    subject = models.CharField('Subject', max_length=20)
    term = models.CharField('Term',max_length=10)
   
    def __unicode__(self):
        return u'%s-%s-%s' %(self.assessment,self.subject,self.term)




class donesubjects(models.Model):
    session = models.CharField('Session', max_length=375)
    exam_type = models.CharField('Exam_type', max_length=75)
    student = models.ForeignKey(Student, max_length=75, null=True, blank=True)
    subject = models.CharField('Subject', max_length=20)
    term = models.CharField('Term',max_length=10)


    def __unicode__(self):
        return u'%s-%s-%s' %(self.exam_type,self.subject,self.term)



class cbtcurrentquestion(models.Model):
    session = models.CharField('Session', max_length=375)
    exam_type = models.CharField('Exam_type', max_length=75)
    student = models.ForeignKey(Student, max_length=75, null=True, blank=True)
    subject = models.CharField('Subject', max_length=20)
    term = models.CharField('Term',max_length=10)
    number = models.CharField('number',max_length=10)

    def __unicode__(self):
        return u'%s-%s-%s-%s' %(self.exam_type,self.subject,self.student,self.number)



class cbtold(models.Model):
    session = models.CharField('Session', max_length=375)
    exam_type = models.CharField('Exam_type', max_length=75)
    student = models.ForeignKey(Student, max_length=75, null=True, blank=True)
    subject = models.CharField('Subject', max_length=20)
    term = models.CharField('Term',max_length=10)
    question = models.ForeignKey(tblquestion,null=False,blank=False,choices=state,default='INACTIVE')
    klass = models.CharField('Class',max_length=10)
    qstcode = models.CharField('Question ID',default=0, max_length=10)

    def __unicode__(self):

        return u' exam : %s ,subject : %s , term : %s' % (self.exam_type,self.subject,self.term)
        

assessment/models.py
from django.db import models

# Create your models here.

CBT/templates/CBT/edit.html
{% extends 'CBT/base.html' %}
{% block sectionTitle %}Success{% endblock %}


{% block content %}



    <div class ="row">
               <table width="100%" class="table  table-bordered " id="dataTables-example">
        <tr>
            <td style="text-align:center;color:black;background-color:#ccccc0;font-size:14px;">
                EDIT ENTRIES
            </td>
        </tr>
    </table>
</div>
        <div style="panel-body">





        <tr >
            <td colspan="20">
               <form action="/cbt/set_qstn/subject/" method="POST">
                  <table width="100%" class="table  table-bordered table-hover" id="dataTables-example">
                   <tr >
                       <td >Session:&nbsp; {{ form.session }}</td>
                       <td >Term:&nbsp;{{ form.term }}</td >
                       <td >Year:&nbsp;{{ form.klass }}</td>              
                       <td >Subject:&nbsp;{{ form.subject }}</td >
                        <td >Exam Type:&nbsp;{{ form.exam_type }}</td >
                       <table>
                    </table>
                   </tr>

                   <div class=="row"><tr><td ><div class="boxopt"> </div></td></tr></div>

    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
            };

            cbtclass();
            //getarm();
            // getterm();
        });
    </script>
    
   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_subject").change(function () {
                autopost2();
            });
            $("#id_arma").change(function () {
                getsubject();
            });
            $("#id_klass").change(function () {
                getcbtsubject();
            });
            $("#id_terhjm").change(function () {
                autopost2();
            });
        });
    </script>





    <script type="text/javascript" language="javascript">
        function cbtclass(){
            var state = $("#id_session").val() ; // i need session to determine my class
            // alert(state);
            var url = "/cbt/enter/ajaxclass/";
            var i = 0;
            var data='userid='+state;
            $("#id_klass").val('');   
            $("#id_klass").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_klass").append(options);

                        getcbtsubject();
                    }
                })
            }
        }

    </script>
 

     <script type="text/javascript" language="javascript">
        function getcbtsubject(){
            var state = $("#id_session").val() + ':'+ $("#id_klass").val();
            var url = "/cbt/getcbtsubject/";
            var i = 0;
            var data='userid='+state;
            $("#id_subject").val('');
            $("#id_subject").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_subject").append(options);
                        autopost2();
                    }
                })
            }
        }

    </script>


    <script type="text/javascript" language="javascript">
        function autopost2(){
            var state = $("#id_session").val()+ ':'+ $("#id_term").val() + ':'+ $("#id_klass").val()+':'+ $("#id_subject").val()+ ':'+ $("#id_exam_type").val();
                // alert (state)
            var url = "/cbt/enter/options/edit/";
            // var url = "/cbt/enter/question/getqstn/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".boxopt").show();
                    $(".boxopt").html(html);

                }
            });
            return false;
        }
    </script>

 </table>
{% endblock %}

CBT/templates/CBT/markguide.html
{% extends 'CBT/base.html' %}
{% block sectionTitle %}Success{% endblock %}


{% block content %}



    <div class ="row">
        <!-- <input class="btn btn-lg btn-success btn-block" name="submit" type= "submit" value="    Log On    "> -->
              <table width="100%" class="table  table-bordered " id="dataTables-example">
        <tr>
            <td style="text-align:center;color:black;background-color:#ccccc0;font-size:14px;">
                MARK GUIDES
            </td>
        </tr>
    </table>
</div>
        <div style="panel-body">





        <tr >
            <td colspan="20">
               <form action="/cbt/set_qstn/subject/" method="POST">
                  <table width="100%" class="table  table-bordered table-hover" id="dataTables-example">
                   <tr >
                       <td >Session:&nbsp; {{ form.session }}</td>
                       <td >Term:&nbsp;{{ form.term }}</td >
                       <td >Year:&nbsp;{{ form.klass }}</td>              
                       <td >Subject:&nbsp;{{ form.subject }}</td >
                        <td >Exam Type:&nbsp;{{ form.exam_type }}</td >
                       <table>
                    </table>
                   </tr>
<tr>
                   <div class=="row"><tr><td ><div class="boxopt"> </div></td></tr></div>
</tr>
    <script>
        $(document).ready(function() {
            var pickerOpts = {
                //appendText: "mm/dd/yy",
                //defaultDate: "+5",
                showOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat:"yy-mm-dd"
            };

            cbtclass();
            //getarm();
            // getterm();
        });
    </script>
    
   <script type="text/javascript" >
        $(document).ready(function() {

            $("#id_subject").change(function () {
                autopost2();
            });
            $("#id_arma").change(function () {
                getsubject();
            });
            $("#id_klass").change(function () {
                getcbtsubject();
            });
            $("#id_terhjm").change(function () {
                autopost2();
            });
        });
    </script>





    <script type="text/javascript" language="javascript">
        function cbtclass(){
            var state = $("#id_session").val() ; // i need session to determine my class
            // alert(state);
            var url = "/cbt/enter/ajaxclass/";
            var i = 0;
            var data='userid='+state;
            $("#id_klass").val('');   
            $("#id_klass").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_klass").append(options);

                        getcbtsubject();
                    }
                })
            }
        }

    </script>
 

     <script type="text/javascript" language="javascript">
        function getcbtsubject(){
            var state = $("#id_session").val() + ':'+ $("#id_klass").val();
            var url = "/cbt/getcbtsubject/";
            var i = 0;
            var data='userid='+state;
            $("#id_subject").val('');
            $("#id_subject").html('');
            if (state != undefined){
                $.ajax({
                    type: "POST",
                    url: url,
                    data:data,
                    success: function(data){
                        var options = '';
                        for (i=0; i<data.length; i++){
                            options += '<option value="' + data[i] +'">' + data[i] + '</option>'
                        }
                        $("#id_subject").append(options);
                        autopost2();
                    }
                })
            }
        }

    </script>


    <script type="text/javascript" language="javascript">
        function autopost2(){
            var state = $("#id_session").val()+ ':'+ $("#id_term").val() + ':'+ $("#id_klass").val()+':'+ $("#id_subject").val()+ ':'+ $("#id_exam_type").val();
                // alert (state)
            var url = "/cbt/markguide/getmg/";
            var i = 0;
            var data='userid='+state;
            $.ajax({
                type:"POST",
                url:url,
                data:data,
                success:function(html) {
                    $(".boxopt").show();
                    $(".boxopt").html(html);

                }
            });
            return false;
        }
    </script>

 </table>
{% endblock %}

CBT/templates/CBT/nosub.html
{% extends 'welcome1.html' %}
{% block sectionTitle %}Success{% endblock %}
{% block content %}

   <span style="font-size:20px;color:black;text-align:center;"> {{varerr}}</span>
{% endblock %}